name: Fetch data

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://docs.google.com/spreadsheets/d/1hQwF3sVDmqJ9rjAku9TIGDjpqrkhtO1QUyvLb5d2QFc/export?format=csv&gid=1980723697
          downloaded_filename: strava.csv
